# Generated by Django 4.2.30 on 2026-09-05 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_verified_artist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='payout_bank_details',
            field=models.TextField(blank=True, help_text='Bank account details for NEFT/RTGS transfers'),
        ),
        migrations.AddField(
            model_name='artist',
            name='payout_upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for gallery sale payouts', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
