# Generated by Django 4.2.30 on 2026-06-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year_created', models.IntegerField()),
                ('style', models.CharField(choices=[('Realism', 'Realism'), ('Impressionism', 'Impressionism'), ('Abstract', 'Abstract'), ('Surrealism', 'Surrealism'), ('Other', 'Other')], default='Other', max_length=50)),
                ('story', models.TextField(blank=True)),
                ('materials', models.CharField(blank=True, max_length=300)),
                ('dimensions', models.CharField(blank=True, max_length=200)),
                ('current_location', models.CharField(blank=True, max_length=300, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='paintings/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
            ],
            options={
                'ordering': ['-year_created'],
            },
        ),
    ]
