# Generated by Django 4.2.30 on 2026-09-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('curator_statement', models.TextField()),
                ('curator_name', models.CharField(default='Curatorial Board', max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='exhibitions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paintings', models.ManyToManyField(blank=True, related_name='exhibitions', to='paintings.painting')),
            ],
            options={
                'ordering': ['-featured', '-start_date', '-created_at'],
            },
        ),
    ]
