# Generated by Django 4.2.30 on 2026-09-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0003_exhibition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_name', models.CharField(max_length=200)),
                ('collector_email', models.EmailField(max_length=254)),
                ('collector_phone', models.CharField(blank=True, max_length=25)),
                ('inquiry_type', models.CharField(choices=[('private_viewing', 'Private Gallery Viewing'), ('condition_report', 'Condition & Provenance Report'), ('acquisition_inquiry', 'Curatorial Acquisition Inquiry'), ('other', 'General Curatorial Question')], default='private_viewing', max_length=35)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'Curator Contacted'), ('completed', 'Completed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='paintings.painting')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
