# Generated by Django 4.2.30 on 2026-09-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='artist_payout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='gallery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='painting',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
