# Generated by Django 6.1 on 2026-09-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0005_order_artist_payout_order_gallery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=7.5, help_text='Gallery commission rate percentage for exhibition/auction sales (typically 7-8%, default 7.50%)', max_digits=4),
        ),
        migrations.AddField(
            model_name='order',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_type',
            field=models.CharField(choices=[('normal', 'Normal Gallery Sale (5%)'), ('exhibition', 'Exhibition Auction Sale (7-8%)')], default='normal', max_length=20),
        ),
    ]
